### PR TITLE
Added responsive-utilities file

### PR DESCRIPTION
**Pull request by shp-novicell**

### CODE REVIEW

**Comment by hesselberg** [comment]
Up, down? Don't they kinda mess up with the idea behind hidden classes?

**Comment by Dan9boi** [comment]
@shp-novicell I think we should remove the up/down classes, and keep the other helper classes.

**Comment by Dan9boi** [comment]
@shp-novicell can you fix this be the end of this week?

**Comment by shp-novicell** [comment]
@Dan9boi Ready!

**Pull request merged**
