### PR TITLE
New gulptask for colorthemes

### PR DESCRIPTION
**Pull request by shp-novicell**

### CODE REVIEW

**Comment by Dan9boi** [comment]
Cool new feature. Did you make some documentation for how to use this? @shp-novicell

**Comment by Dan9boi** [comment]
Very cool! Well done @shp-novicell and @hesselberg 💯

**Comment by hesselberg** [comment]
I actually had a discussion with @Havmoeller about this -- I'm not sure that this is something that we should add to the default frontend package.

Theming is done very differently depending on a project by project scenario. Is this something that we will be using as a default thing?

**Comment by hesselberg** [comment]
@Dan9boi oh, you merged it already :-)

**Pull request merged**
