### PR TITLE
Gulp task "styles" fixed. Lint support added.

### LINKED ISSUE #262: Stylelint is not working in gulp task
Stylelint is declared in gulp "styles" task but it does not work. Perhaps it should be implemented differently

### PR DESCRIPTION
**Pull request by ankeris**
Here, I have changed "styles" task where I have nested stylelint function into postcss-import as a plugin. I did that because stylelint was not working before.
Added .prettierrc for any additional options.
This fixes #262 and #261

### CODE REVIEW

**Comment by ankeris** [comment]
There is a new commit. However, in master.css, these files are being linted:
```css
@import '../../node_modules/priority-nav/dist/priority-nav-core.css';
@import '../../node_modules/flickity/dist/flickity.css';
```
I tried adding ` /* stylelint-disable-line */ ` but it does not work because the import line itself is linted correctly.

**Comment by heense** [comment]
Can we make it ignore node_modules? 
Maybe take a look at [--ignore-path](https://prettier.io/docs/en/cli.html#ignore-path) or [Ignoring the line](https://prettier.io/docs/en/ignore.html)

**Comment by heense** [comment]
It look's like it's having a hard time formating the .hbs files. 
I think we just can skip those until the support gets better.

If you add the code below to your workspace settings, it will ignore them.
"[handlebars]": { "editor.formatOnSave": false },

**Comment by Dan9boi** [comment]
There seems to be an issue with the [settings ](https://github.com/Novicell/novicell-frontend/wiki/Prettier-extension-on-VSCode#how-to) not agreeing with eslint in the SPA nuxt setup.

Remember to test this aswell @heense

**Comment by ankeris** [comment]
Hey, in order to use prettier for Vue, **parser** has to be added either in .prettierrc or IDE settings: [More about parsers](https://prettier.io/docs/en/options.html)

**Pull request merged**
