### PR TITLE
Issue #317: Use vue.min.js in non-development environments

### LINKED ISSUE #317: Use production Vue
When building for production (`build:prod`) development distribution of Vue is included. (Verifiable by console warning if you install vue and import it in the project)

I submit a pull request to include .min.js distribution (production mode build) in production environment, but I am not sure why Vue needs to be explicitly aliased there rather than imported.

### PR DESCRIPTION
**Pull request by sebimoe**
Resolves #317

### CODE REVIEW

**Comment by sebimoe** [comment]
Checks pass as netlify can't deploy - noted in https://github.com/Novicell/novicell-frontend/pull/316

**Comment by ankeris** [comment]
@sebimoe, Thank you for the change.
However I am not really sure why Netlify build is failing, though it has nothing to do with your feature

**Comment by hesselberg** [comment]
> @sebimoe, Thank you for the change.
> However I am not really sure why Netlify build is failing, though it has nothing to do with your feature

Happens as the favicon is missing, and we have changed the netlify build command to generate the favicon.

This has been addressed in #319

**Comment by ankeris** [comment]
> > @sebimoe, Thank you for the change.
> > However I am not really sure why Netlify build is failing, though it has nothing to do with your feature
> 
> Happens as the favicon is missing, and we have changed the netlify build command to generate the favicon.
> 
> This has been addressed in #319

@hesselberg 
I have tested it with generated icon in assets folder.
Nevertheless, Netlify does not seem to find it.
The generated icon even exists in this PR

**Pull request merged**
