### PR TITLE
Renamed Modules to modules

### PR DESCRIPTION
**Pull request by hesselberg**
Any reason why the modules folder was capitalised?

Prettier also did some formatting.

### CODE REVIEW

**Comment by hesselberg** [comment]
Aha, so this is why Netlify failed in my other project. The modules folder does need to be capitalised?

**Comment by magnify** [comment]
@Dan9boi or @ankeris do you have suggestions?

**Comment by magnify** [comment]
Can confirm the issue with a clean clone of the repo.

- Renamed "**M**odules" to "**m**odules"
- Replaced references

**Comment by magnify** [comment]
Found a fix by removing the modules folder and adding it again. Suspect this is because of Github not recognising case when renaming. Tested on other repo with build to Netlify.

**Comment by hesselberg** [comment]
Nice

**Pull request merged**
