### PR TITLE
Update package.json for node support

### PR DESCRIPTION
**Pull request by ramiejleh**
Add natives package to fix gulp when updating to node 10.x.x

### CODE REVIEW

**Comment by Dan9boi** [comment]
@korfitz please test everything is working in node v. 10.x.x

**Comment by ramiejleh** [comment]
Make sure to have gulp installed globally on your computer before testing.

**Comment by Dan9boi** [comment]
@ankeris make sure to checkout the branch of this pull request, for testing.

**Comment by ankeris** [comment]
Hey @ramiejleh few packages were updated and 'gulp' seems to work with Node 10.x could you test it? This also fixes #245

**Pull request merged**
