### PR TITLE
Feature/overlapping elements#258

### PR DESCRIPTION
**Pull request by Henrikschytze**
Fixing #258 
Added both an overlap demonstration under molecules and a page demonstrating it more in depth.

### CODE REVIEW

**Comment by Dan9boi** [comment]
Should we do breakpoint based overlaps?
I would like it to be `min-width` media queries.
Do the equivalent of the media queries in `variables.css`

Something like:
```css
.overlap-item-xs--left {...}
.overlap-item-sm--left {...}
.overlap-item-md--left {...}
.overlap-item-lg--left {...}
```
and so on, for every overlap, we have...
Don't you agreee @tbb2 ?

**Comment by Dan9boi** [comment]
@Henrikschytze can you make the media queries, then @Bjornnyborg wil review 💯

**Comment by Henrikschytze** [comment]
I will @Dan9boi, I'm also making a few changes that Daniel requested 👍

**Comment by Henrikschytze** [comment]
I added the media queries, so it is ready for review @Bjornnyborg 👍

**Pull request merged**
